name: sns_comment_sync_problem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.0
  json_annotation: ^4.3.0
  flutter_riverpod: ^2.0.0
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.1.0
  freezed: ^2.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
